# Generated by Django 3.0.8 on 2020-07-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_subscriber_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='created_date',
        ),
    ]
